try
{
    aFunction("Welcome gp!");
}
catch(err)
{
    console.log(err.message);
}

console.log("Hello gp!");